// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<string>("amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("imagen_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("metros_cuadrados")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ocupantes")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Tarifa = 200.0,
                            amenidad = "",
                            detalle = "Detalle...",
                            fecha_actualizacion = new DateTime(2023, 9, 18, 23, 2, 14, 822, DateTimeKind.Local).AddTicks(4253),
                            fecha_creacion = new DateTime(2023, 9, 18, 23, 2, 14, 822, DateTimeKind.Local).AddTicks(4243),
                            imagen_url = "",
                            metros_cuadrados = 50,
                            nombre = "Villa Real",
                            ocupantes = 4
                        },
                        new
                        {
                            id = 2,
                            Tarifa = 150.0,
                            amenidad = "",
                            detalle = "Detalle...",
                            fecha_actualizacion = new DateTime(2023, 9, 18, 23, 2, 14, 822, DateTimeKind.Local).AddTicks(4255),
                            fecha_creacion = new DateTime(2023, 9, 18, 23, 2, 14, 822, DateTimeKind.Local).AddTicks(4255),
                            imagen_url = "",
                            metros_cuadrados = 40,
                            nombre = "Villa Premium",
                            ocupantes = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
